name: ChatMute
author: AlexanderIIGAMEFEAL
version: 0.0.5
main: main.Main
api-version: 1.16

commands:
   mute:
      description: Mutes a player
      usage: /mute <time in hours>
      
   rlmuteconfig:
      description: Reloads the config file
      usage: /rlmuteconfig </>